name: Mermaid Workflow

on:
  push:
    branches:
      - main  # 可以根据需要修改分支
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 指定 Node.js 版本

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate Mermaid diagrams
        run: |
        echo "graph TD; A-->B; A-->C; B-->D; C-->D;" > test.mmd
        mmdc -i test.mmd -o test.svg 
